name: "WAF RE Destroy"

on:
  push:
    branches:
      - destroy-waf-re
  pull_request:

jobs:
  terraform_xc:
    name: "F5XC WAAP"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workflow-guides/waf/f5-xc-waf-on-re/terraform/xc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform { 
            cloud {
              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
              workspaces {
                name = "${{ secrets.TF_CLOUD_WORKSPACE_XC }}"
              }
            }
          }
          EOF
          echo "${{secrets.P12}}" | base64 -d > api.p12
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/destroy-waf-re' && github.event_name == 'push'
        run: terraform destroy -auto-approve -input=false
